### ISSUE TITLE
Faces with >4 vertices not supported

### ISSUE THREAD

**Issue by random-geek** [jonnenauha/obj-simplify#10]
This is a neat tool, you earned my star! However, it seems that any faces with over 4 vertices are truncated to just the first 4 vertices when exporting, which is kind of inconvenient since I have models with octagonal faces.

It seems like the upper index limit [here](https://github.com/jonnenauha/obj-simplify/blob/a2f5cd9b44e10035ea5e1893eb63c9dbff2f7f66/objectfile/structs.go#L443) could simply be removed to fix the issue, although I'm not super familiar with the code base or the language.

**Comment by jonnenauha** [comment]
I havent touched this repo in many years, my use of obj is long past :) 

You can quite easily tweak the codebase and build new binary. If you are willing to learn how to setup go the readme has instructions https://github.com/jonnenauha/obj-simplify#dev-quickstart This is the GOPATH based approach as go modules did not exist back then.

Or you could install latest go, clone this repo, port to go modules using this.

```
go mod init
// change code
go build
```

**Comment by jonnenauha** [comment]
I havent touched this repo in many years, my use of obj is long past :) 

You can quite easily tweak the codebase and build new binary. If you are willing to learn how to setup go the readme has instructions https://github.com/jonnenauha/obj-simplify#dev-quickstart This is the GOPATH based approach as go modules did not exist back then.

Or you could install latest go, clone this repo, port to go modules using this.

```
go mod init
// change code
go build
```

**Comment by random-geek** [comment]
Understood, thank you!
